// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Entities.AsasLandZone;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Infrastructure.AgentDataModels.Configurations
{
    public partial class AgentBatchConfiguration : IEntityTypeConfiguration<AgentBatch>
    {
        public void Configure(EntityTypeBuilder<AgentBatch> entity)
        {
            entity.ToTable("Batches");

        }

    }
}
