// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Application.Common.Interfaces.AsasLandingzoneDb;
using Application.Common.Interfaces.AsasLandingzoneDb.Dtos;
using Domain.Entities.AsasLandZone;
using Infrastructure.AgentDataModels.Configurations;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Infrastructure.AgentDataModels;

public partial class AsasLandZoneDb : DbContext, IAsasLandZoneDb
{
    private readonly ILogger<IAsasLandZoneDb> _logger;

    public AsasLandZoneDb(DbContextOptions<AsasLandZoneDb> options, ILogger<IAsasLandZoneDb> logger) : base(options)
    {
        _logger = logger;
    }
    public DbSet<LZAgentBatch> AgentBatchs => Set<LZAgentBatch>();
    public DbSet<LZSchemaType> SchemaTypes => Set<LZSchemaType>();

    public Task<(bool isValid, string errorMessage)> Execute_InsertNewPackagetForAgentBatch_SP(InsertNewPackageSpInput input, CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }

    public Task<(bool isValid, string errorMessage)> Execute_StartNewBatchFroAgent_SP(StartNewBatchSPInput input, CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }

    public Task<(bool isValid, string errorMessage)> Execute_StopCurrentForAgentBatch_SP(StopCurrentBatchSPInput input, CancellationToken cancellationToken)
    {
        throw new NotImplementedException();
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        builder.ApplyConfiguration(new LZAgentBatchConfiguration());
        builder.ApplyConfiguration(new LZSchemaTypeConfiguration());
    }
}
